name: Deploy Frontend

on:
  push:
    branches:
      - front-deploy
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            frontend

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: frontend
        run: bun install --frozen-lockfile

      - name: Build frontend
        working-directory: frontend
        run: bun run build

      - name: Clean server folder
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            TARGET="${{ secrets.SSH_TARGET_DIR }}"
            mkdir -p "$TARGET"
            find "$TARGET" -mindepth 1 -delete
          script_stop: true
          debug: false

      - name: Upload build
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "frontend/out/*"
          target: ${{ secrets.SSH_TARGET_DIR }}
          strip_components: 2
